using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HousePicker : MonoBehaviour
{
    public enum HouseSelector
    {
        Shop_1,
        Shop_2,
        Shop_3,
        Shop_4,
        Apartment_1,
        Apartment_2,
        Apartment_3,
        Apartment_4,
        Apartment_5,
        Apartment_6,
        Apartment_7,
        Apartment_8,
        Apartment_9,
        Apartment_10,
        Apartment_11,
        Apartment_12,
        Mabati_house_1,
        Mabati_house_2,
        Mabati_house_3,

    }
    public HouseSelector HouseSelector_;
    public List<GameObject> Houses = new List<GameObject>();
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        switch(HouseSelector_)
        {
            case HouseSelector.Shop_1:
            Houses[0].SetActive(true);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Shop_2:
            Houses[0].SetActive(false);
            Houses[1].SetActive(true);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Shop_3:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(true);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Shop_4:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(true);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_1:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(true);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_2:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(true);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_3:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(true);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_4:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(true);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_5:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(true);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_6:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(true);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_7:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(true);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_8:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(true);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_9:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(true);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_10:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(true);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_11:
            Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(true);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Apartment_12:
           Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(true);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Mabati_house_1:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(true);
            Houses[17].SetActive(false);
            Houses[18].SetActive(false);
            break;
            case HouseSelector.Mabati_house_2:
             Houses[0].SetActive(false);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(true);
            Houses[18].SetActive(false);

            break;
            case HouseSelector.Mabati_house_3:
            Houses[0].SetActive(true);
            Houses[1].SetActive(false);
            Houses[2].SetActive(false);
            Houses[3].SetActive(false);
            Houses[4].SetActive(false);
            Houses[5].SetActive(false);
            Houses[6].SetActive(false);
            Houses[7].SetActive(false);
            Houses[8].SetActive(false);
            Houses[9].SetActive(false);
            Houses[10].SetActive(false);
            Houses[11].SetActive(false);
            Houses[12].SetActive(false);
            Houses[13].SetActive(false);
            Houses[14].SetActive(false);
            Houses[15].SetActive(false);
            Houses[16].SetActive(false);
            Houses[17].SetActive(false);
            Houses[18].SetActive(true);
            break;
        }
    }
}
